"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-30 14:57:25.847968+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_type', sa.Text(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_label', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('target_type', sa.Text(), nullable=False),
    sa.Column('target_id', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('request_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("actor_type IN ('user', 'api_key', 'system')", name=op.f('ck_audit_events_actor_type')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    op.create_index('ix_audit_events_action', 'audit_events', ['action'], unique=False)
    op.create_index('ix_audit_events_created_at', 'audit_events', ['created_at'], unique=False)
    op.create_index('ix_audit_events_target', 'audit_events', ['target_type', 'target_id'], unique=False)
    op.create_table('criteria',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('dimension', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('question', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('rubric', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('scale_min', sa.Float(), server_default=sa.text('0'), nullable=False),
    sa.Column('scale_max', sa.Float(), server_default=sa.text('5'), nullable=False),
    sa.Column('builtin', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("dimension IN ('quality', 'coherence', 'reasoning', 'safety', 'robustness', 'cost', 'latency', 'ux')", name=op.f('ck_criteria_dimension')),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_criteria'))
    )
    op.create_table('error_types',
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('default_severity', sa.Text(), nullable=False),
    sa.Column('dimension', sa.Text(), nullable=False),
    sa.Column('builtin', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("default_severity IN ('low', 'medium', 'high', 'critical')", name=op.f('ck_error_types_default_severity')),
    sa.CheckConstraint("dimension IN ('quality', 'coherence', 'reasoning', 'safety', 'robustness', 'cost', 'latency', 'ux')", name=op.f('ck_error_types_dimension')),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_error_types'))
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), server_default=sa.text("'viewer'"), nullable=False),
    sa.Column('clearance', sa.SmallInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('avatar_color', sa.Text(), server_default=sa.text("'#ea580c'"), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('viewer', 'evaluator', 'editor', 'maintainer', 'admin')", name=op.f('ck_users_role')),
    sa.CheckConstraint('clearance BETWEEN 0 AND 3', name=op.f('ck_users_clearance_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index('uq_users_email', 'users', ['email'], unique=True)
    op.create_table('agents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('provider', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('archived', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_agents_owner_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agents'))
    )
    op.create_index('uq_agents_slug', 'agents', ['slug'], unique=True)
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('prefix', sa.Text(), nullable=False),
    sa.Column('key_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('clearance', sa.SmallInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('viewer', 'evaluator', 'editor', 'maintainer', 'admin')", name=op.f('ck_api_keys_role')),
    sa.CheckConstraint('clearance BETWEEN 0 AND 3', name=op.f('ck_api_keys_clearance_range')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_api_keys_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_keys'))
    )
    op.create_index('uq_api_keys_prefix', 'api_keys', ['prefix'], unique=True)
    op.create_table('datasets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('context', 'gold')", name=op.f('ck_datasets_kind')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_datasets_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_datasets'))
    )
    op.create_index('uq_datasets_slug', 'datasets', ['slug'], unique=True)
    op.create_table('evaluation_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('dimension_weights', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('criterion_weights', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('normalization', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('gates', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('judge_ids', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('aggregation', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('criteria', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('rules', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('use_human_scores', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('pass_threshold', sa.Float(), server_default=sa.text('70'), nullable=False),
    sa.Column('is_latest', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_evaluation_configs_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluation_configs')),
    sa.UniqueConstraint('key', 'version', name=op.f('uq_evaluation_configs_key_version'))
    )
    op.create_index('ix_evaluation_configs_key_is_latest', 'evaluation_configs', ['key', 'is_latest'], unique=False)
    op.create_table('model_configurations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('model_version', sa.Text(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('top_p', sa.Float(), nullable=True),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('seed', sa.Integer(), nullable=True),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('input_cost_per_mtok', sa.Float(), nullable=True),
    sa.Column('output_cost_per_mtok', sa.Float(), nullable=True),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_model_configurations_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_configurations'))
    )
    op.create_index('ix_model_configurations_content_hash', 'model_configurations', ['content_hash'], unique=False)
    op.create_table('prompt_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('variables', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_prompt_versions_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prompt_versions')),
    sa.UniqueConstraint('name', 'version', name=op.f('uq_prompt_versions_name_version'))
    )
    op.create_table('provider_credentials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('base_url', sa.Text(), nullable=True),
    sa.Column('secret_encrypted', sa.Text(), nullable=True),
    sa.Column('headers_encrypted', sa.Text(), nullable=True),
    sa.Column('secret_hint', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('openai', 'anthropic', 'nova', 'orbit', 'http')", name=op.f('ck_provider_credentials_kind')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_provider_credentials_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_credentials'))
    )
    op.create_index('uq_provider_credentials_name', 'provider_credentials', ['name'], unique=True)
    op.create_table('scenarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('parent_scenario_id', sa.UUID(), nullable=True),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('variant_label', sa.Text(), nullable=True),
    sa.Column('visibility', sa.Text(), server_default=sa.text("'public'"), nullable=False),
    sa.Column('classification', sa.SmallInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('fresh_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('latest_version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('archived', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("visibility IN ('public', 'private', 'fresh')", name=op.f('ck_scenarios_visibility')),
    sa.CheckConstraint('classification BETWEEN 0 AND 3', name=op.f('ck_scenarios_classification_range')),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_scenarios_owner_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_scenario_id'], ['scenarios.id'], name=op.f('fk_scenarios_parent_scenario_id_scenarios'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scenarios'))
    )
    op.create_index('ix_scenarios_category', 'scenarios', ['category'], unique=False)
    op.create_index('ix_scenarios_family_id', 'scenarios', ['family_id'], unique=False)
    op.create_index('uq_scenarios_slug', 'scenarios', ['slug'], unique=True)
    op.create_table('tool_configurations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('tools', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_tool_configurations_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tool_configurations')),
    sa.UniqueConstraint('name', 'version', name=op.f('uq_tool_configurations_name_version'))
    )
    op.create_table('agent_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Text(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('adapter_kind', sa.Text(), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=True),
    sa.Column('model_configuration_id', sa.UUID(), nullable=True),
    sa.Column('prompt_version_id', sa.UUID(), nullable=True),
    sa.Column('system_prompt', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('tool_configuration_id', sa.UUID(), nullable=True),
    sa.Column('context_config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('memory_config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('orchestration_config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('adapter_config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('credential_id', sa.UUID(), nullable=True),
    sa.Column('budget', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('max_concurrency', sa.Integer(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('changelog', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('parent_version_id', sa.UUID(), nullable=True),
    sa.Column('contamination', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("adapter_kind IN ('openai', 'anthropic', 'nova', 'custom_api', 'mock')", name=op.f('ck_agent_versions_adapter_kind')),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_agent_versions_agent_id_agents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_agent_versions_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['credential_id'], ['provider_credentials.id'], name=op.f('fk_agent_versions_credential_id_provider_credentials'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['model_configuration_id'], ['model_configurations.id'], name=op.f('fk_agent_versions_model_configuration_id_model_configurations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parent_version_id'], ['agent_versions.id'], name=op.f('fk_agent_versions_parent_version_id_agent_versions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['prompt_version_id'], ['prompt_versions.id'], name=op.f('fk_agent_versions_prompt_version_id_prompt_versions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tool_configuration_id'], ['tool_configurations.id'], name=op.f('fk_agent_versions_tool_configuration_id_tool_configurations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_versions')),
    sa.UniqueConstraint('agent_id', 'version', name=op.f('uq_agent_versions_agent_id_version')),
    sa.UniqueConstraint('agent_id', 'version_number', name=op.f('uq_agent_versions_agent_id_version_number'))
    )
    op.create_index('ix_agent_versions_content_hash', 'agent_versions', ['content_hash'], unique=False)
    op.create_table('benchmarks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('evaluation_config_id', sa.UUID(), nullable=False),
    sa.Column('repetitions', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('archived', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('repetitions BETWEEN 1 AND 20', name=op.f('ck_benchmarks_repetitions_range')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_benchmarks_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['evaluation_config_id'], ['evaluation_configs.id'], name=op.f('fk_benchmarks_evaluation_config_id_evaluation_configs'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_benchmarks'))
    )
    op.create_index('uq_benchmarks_slug', 'benchmarks', ['slug'], unique=True)
    op.create_table('judges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('model_version', sa.Text(), nullable=True),
    sa.Column('temperature', sa.Float(), server_default=sa.text('0'), nullable=False),
    sa.Column('max_tokens', sa.Integer(), server_default=sa.text('1500'), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('rubric_template', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('criteria', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('weight', sa.Float(), server_default=sa.text('1'), nullable=False),
    sa.Column('base_url', sa.Text(), nullable=True),
    sa.Column('credential_id', sa.UUID(), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_latest', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("provider IN ('openai', 'anthropic', 'heuristic')", name=op.f('ck_judges_provider')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_judges_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['credential_id'], ['provider_credentials.id'], name=op.f('fk_judges_credential_id_provider_credentials'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_judges')),
    sa.UniqueConstraint('key', 'version', name=op.f('uq_judges_key_version'))
    )
    op.create_index('ix_judges_key_is_latest', 'judges', ['key', 'is_latest'], unique=False)
    op.create_table('scenario_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scenario_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('difficulty', sa.Text(), nullable=False),
    sa.Column('input', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('constraints', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('expected_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('expected_behavior', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('criteria', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('rules', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('tool_mocks', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=True),
    sa.Column('canary', sa.Text(), nullable=False),
    sa.Column('changelog', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("difficulty IN ('easy', 'medium', 'hard', 'expert')", name=op.f('ck_scenario_versions_difficulty')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_scenario_versions_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_scenario_versions_dataset_id_datasets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], name=op.f('fk_scenario_versions_scenario_id_scenarios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scenario_versions')),
    sa.UniqueConstraint('scenario_id', 'version', name=op.f('uq_scenario_versions_scenario_id_version'))
    )
    op.create_index('ix_scenario_versions_content_hash', 'scenario_versions', ['content_hash'], unique=False)
    op.create_table('benchmark_agents',
    sa.Column('benchmark_id', sa.UUID(), nullable=False),
    sa.Column('agent_version_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['agent_version_id'], ['agent_versions.id'], name=op.f('fk_benchmark_agents_agent_version_id_agent_versions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['benchmark_id'], ['benchmarks.id'], name=op.f('fk_benchmark_agents_benchmark_id_benchmarks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('benchmark_id', 'agent_version_id', name=op.f('pk_benchmark_agents'))
    )
    op.create_table('benchmark_executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('benchmark_id', sa.UUID(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('evaluation_config_id', sa.UUID(), nullable=False),
    sa.Column('repetitions', sa.Integer(), nullable=False),
    sa.Column('matrix', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('total_runs', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('completed_runs', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('failed_runs', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('trigger', sa.Text(), server_default=sa.text("'ui'"), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('triggered_by', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'queued', 'running', 'aggregating', 'completed', 'failed', 'cancelled')", name=op.f('ck_benchmark_executions_status')),
    sa.ForeignKeyConstraint(['benchmark_id'], ['benchmarks.id'], name=op.f('fk_benchmark_executions_benchmark_id_benchmarks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evaluation_config_id'], ['evaluation_configs.id'], name=op.f('fk_benchmark_executions_evaluation_config_id_evaluation_configs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], name=op.f('fk_benchmark_executions_triggered_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_benchmark_executions')),
    sa.UniqueConstraint('benchmark_id', 'number', name=op.f('uq_benchmark_executions_benchmark_id_number'))
    )
    op.create_index('ix_benchmark_executions_benchmark_id_created_at', 'benchmark_executions', ['benchmark_id', 'created_at'], unique=False)
    op.create_table('benchmark_scenarios',
    sa.Column('benchmark_id', sa.UUID(), nullable=False),
    sa.Column('scenario_id', sa.UUID(), nullable=False),
    sa.Column('scenario_version_id', sa.UUID(), nullable=True),
    sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['benchmark_id'], ['benchmarks.id'], name=op.f('fk_benchmark_scenarios_benchmark_id_benchmarks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], name=op.f('fk_benchmark_scenarios_scenario_id_scenarios'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['scenario_version_id'], ['scenario_versions.id'], name=op.f('fk_benchmark_scenarios_scenario_version_id_scenario_versions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('benchmark_id', 'scenario_id', name=op.f('pk_benchmark_scenarios'))
    )
    op.create_table('experiments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('hypothesis', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('baseline_version_id', sa.UUID(), nullable=False),
    sa.Column('candidate_version_id', sa.UUID(), nullable=False),
    sa.Column('benchmark_id', sa.UUID(), nullable=True),
    sa.Column('evaluation_config_id', sa.UUID(), nullable=False),
    sa.Column('repetitions', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('total_runs', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('completed_runs', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('failed_runs', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('comparison', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('source_feedback_report_id', sa.UUID(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('trigger', sa.Text(), server_default=sa.text("'ui'"), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'queued', 'running', 'aggregating', 'completed', 'failed', 'cancelled')", name=op.f('ck_experiments_status')),
    sa.CheckConstraint('repetitions BETWEEN 1 AND 20', name=op.f('ck_experiments_repetitions_range')),
    sa.ForeignKeyConstraint(['baseline_version_id'], ['agent_versions.id'], name=op.f('fk_experiments_baseline_version_id_agent_versions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['benchmark_id'], ['benchmarks.id'], name=op.f('fk_experiments_benchmark_id_benchmarks'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['candidate_version_id'], ['agent_versions.id'], name=op.f('fk_experiments_candidate_version_id_agent_versions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_experiments_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['evaluation_config_id'], ['evaluation_configs.id'], name=op.f('fk_experiments_evaluation_config_id_evaluation_configs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_feedback_report_id'], ['feedback_reports.id'], name=op.f('fk_experiments_source_feedback_report_id_feedback_reports'), ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experiments'))
    )
    op.create_index('ix_experiments_created_at', 'experiments', ['created_at'], unique=False)
    op.create_table('judge_cache',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('judge_id', sa.UUID(), nullable=False),
    sa.Column('response', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('hits', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['judge_id'], ['judges.id'], name=op.f('fk_judge_cache_judge_id_judges'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_judge_cache'))
    )
    op.create_table('evaluation_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('origin', sa.Text(), nullable=False),
    sa.Column('benchmark_execution_id', sa.UUID(), nullable=True),
    sa.Column('experiment_id', sa.UUID(), nullable=True),
    sa.Column('arm', sa.Text(), nullable=True),
    sa.Column('scenario_id', sa.UUID(), nullable=False),
    sa.Column('scenario_version_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('agent_version_id', sa.UUID(), nullable=False),
    sa.Column('evaluation_config_id', sa.UUID(), nullable=False),
    sa.Column('repetition', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('status_detail', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('error_type', sa.Text(), nullable=True),
    sa.Column('manifest', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('manifest_hash', sa.Text(), nullable=False),
    sa.Column('otel_trace_id', sa.Text(), nullable=False),
    sa.Column('evaluation_round', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('composite_score', sa.Float(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('gate_failed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('queued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("arm IN ('baseline', 'candidate')", name=op.f('ck_evaluation_runs_arm')),
    sa.CheckConstraint("origin IN ('adhoc', 'benchmark', 'experiment')", name=op.f('ck_evaluation_runs_origin')),
    sa.CheckConstraint("status IN ('pending', 'running', 'evaluating', 'completed', 'failed', 'cancelled')", name=op.f('ck_evaluation_runs_status')),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_evaluation_runs_agent_id_agents'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['agent_version_id'], ['agent_versions.id'], name=op.f('fk_evaluation_runs_agent_version_id_agent_versions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['benchmark_execution_id'], ['benchmark_executions.id'], name=op.f('fk_evaluation_runs_benchmark_execution_id_benchmark_executions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_evaluation_runs_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['evaluation_config_id'], ['evaluation_configs.id'], name=op.f('fk_evaluation_runs_evaluation_config_id_evaluation_configs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], name=op.f('fk_evaluation_runs_experiment_id_experiments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], name=op.f('fk_evaluation_runs_scenario_id_scenarios'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['scenario_version_id'], ['scenario_versions.id'], name=op.f('fk_evaluation_runs_scenario_version_id_scenario_versions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluation_runs'))
    )
    op.create_index('ix_evaluation_runs_agent_version_id_created_at', 'evaluation_runs', ['agent_version_id', 'created_at'], unique=False)
    op.create_index('ix_evaluation_runs_benchmark_execution_id', 'evaluation_runs', ['benchmark_execution_id'], unique=False)
    op.create_index('ix_evaluation_runs_created_at', 'evaluation_runs', ['created_at'], unique=False)
    op.create_index('ix_evaluation_runs_experiment_id_arm', 'evaluation_runs', ['experiment_id', 'arm'], unique=False)
    op.create_index('ix_evaluation_runs_otel_trace_id', 'evaluation_runs', ['otel_trace_id'], unique=False)
    op.create_index('ix_evaluation_runs_scenario_id', 'evaluation_runs', ['scenario_id'], unique=False)
    op.create_index('ix_evaluation_runs_status', 'evaluation_runs', ['status'], unique=False)
    op.create_table('experiment_scenarios',
    sa.Column('experiment_id', sa.UUID(), nullable=False),
    sa.Column('scenario_version_id', sa.UUID(), nullable=False),
    sa.Column('scenario_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], name=op.f('fk_experiment_scenarios_experiment_id_experiments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], name=op.f('fk_experiment_scenarios_scenario_id_scenarios'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['scenario_version_id'], ['scenario_versions.id'], name=op.f('fk_experiment_scenarios_scenario_version_id_scenario_versions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('experiment_id', 'scenario_version_id', name=op.f('pk_experiment_scenarios'))
    )
    op.create_table('composite_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('evaluation_config_id', sa.UUID(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('raw_value', sa.Float(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('gate_failed', sa.Boolean(), nullable=False),
    sa.Column('dimensions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('gates', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('missing_dimensions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('formula', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_config_id'], ['evaluation_configs.id'], name=op.f('fk_composite_scores_evaluation_config_id_evaluation_configs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['evaluation_runs.id'], name=op.f('fk_composite_scores_run_id_evaluation_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_composite_scores')),
    sa.UniqueConstraint('run_id', 'round', 'evaluation_config_id', name=op.f('uq_composite_scores_run_id_round_evaluation_config_id'))
    )
    op.create_table('dataset_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_dataset_items_dataset_id_datasets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['evaluation_runs.id'], name=op.f('fk_dataset_items_run_id_evaluation_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dataset_items')),
    sa.UniqueConstraint('dataset_id', 'key', name=op.f('uq_dataset_items_dataset_id_key'))
    )
    op.create_index('ix_dataset_items_run_id', 'dataset_items', ['run_id'], unique=False)
    op.create_table('evaluations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=True),
    sa.Column('evaluation_config_id', sa.UUID(), nullable=True),
    sa.Column('evaluator_kind', sa.Text(), nullable=False),
    sa.Column('evaluator_key', sa.Text(), nullable=False),
    sa.Column('criterion_key', sa.Text(), nullable=False),
    sa.Column('dimension', sa.Text(), nullable=False),
    sa.Column('raw_score', sa.Float(), nullable=False),
    sa.Column('scale_min', sa.Float(), nullable=False),
    sa.Column('scale_max', sa.Float(), nullable=False),
    sa.Column('normalized_score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), server_default=sa.text('1'), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('judge_id', sa.UUID(), nullable=True),
    sa.Column('judge_version', sa.Integer(), nullable=True),
    sa.Column('prompt_hash', sa.Text(), nullable=True),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cached', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('human_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("dimension IN ('quality', 'coherence', 'reasoning', 'safety', 'robustness', 'cost', 'latency', 'ux')", name=op.f('ck_evaluations_dimension')),
    sa.CheckConstraint("evaluator_kind IN ('rule', 'metric', 'llm_judge', 'human', 'aggregate')", name=op.f('ck_evaluations_evaluator_kind')),
    sa.CheckConstraint('length(btrim(explanation)) > 0', name=op.f('ck_evaluations_explanation_required')),
    sa.ForeignKeyConstraint(['evaluation_config_id'], ['evaluation_configs.id'], name=op.f('fk_evaluations_evaluation_config_id_evaluation_configs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['human_user_id'], ['users.id'], name=op.f('fk_evaluations_human_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['judge_id'], ['judges.id'], name=op.f('fk_evaluations_judge_id_judges'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['evaluation_runs.id'], name=op.f('fk_evaluations_run_id_evaluation_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluations'))
    )
    op.create_index('ix_evaluations_criterion_key', 'evaluations', ['criterion_key'], unique=False)
    op.create_index('ix_evaluations_judge_id', 'evaluations', ['judge_id'], unique=False)
    op.create_index('ix_evaluations_run_id_round', 'evaluations', ['run_id', 'round'], unique=False)
    op.create_table('execution_traces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_latency_ms', sa.Float(), nullable=True),
    sa.Column('input', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('output_text', sa.Text(), nullable=True),
    sa.Column('output_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('messages', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('input_tokens', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('output_tokens', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('total_tokens', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('model_calls', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('tool_calls', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('event_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['evaluation_runs.id'], name=op.f('fk_execution_traces_run_id_evaluation_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_execution_traces'))
    )
    op.create_index('uq_execution_traces_run_id', 'execution_traces', ['run_id'], unique=True)
    op.create_table('feedback_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scope', sa.Text(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('benchmark_execution_id', sa.UUID(), nullable=True),
    sa.Column('experiment_id', sa.UUID(), nullable=True),
    sa.Column('agent_version_id', sa.UUID(), nullable=True),
    sa.Column('round', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('strengths', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('weaknesses', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('recommendations', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('priority_actions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('generator', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("scope IN ('run', 'benchmark', 'experiment')", name=op.f('ck_feedback_reports_scope')),
    sa.ForeignKeyConstraint(['agent_version_id'], ['agent_versions.id'], name=op.f('fk_feedback_reports_agent_version_id_agent_versions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['benchmark_execution_id'], ['benchmark_executions.id'], name=op.f('fk_feedback_reports_benchmark_execution_id_benchmark_executions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], name=op.f('fk_feedback_reports_experiment_id_experiments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['evaluation_runs.id'], name=op.f('fk_feedback_reports_run_id_evaluation_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feedback_reports'))
    )
    op.create_index('ix_feedback_reports_benchmark_execution_id', 'feedback_reports', ['benchmark_execution_id'], unique=False)
    op.create_index('ix_feedback_reports_experiment_id', 'feedback_reports', ['experiment_id'], unique=False)
    op.create_index('ix_feedback_reports_run_id', 'feedback_reports', ['run_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('queue', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'queued'"), nullable=False),
    sa.Column('priority', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('max_attempts', sa.Integer(), server_default=sa.text('3'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('dedupe_key', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('locked_by', sa.Text(), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('run_after', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('execute_run', 'evaluate_run', 'finalize_execution', 'finalize_experiment')", name=op.f('ck_jobs_kind')),
    sa.CheckConstraint("queue IN ('execution', 'evaluation')", name=op.f('ck_jobs_queue')),
    sa.CheckConstraint("status IN ('queued', 'running', 'succeeded', 'failed', 'cancelled')", name=op.f('ck_jobs_status')),
    sa.ForeignKeyConstraint(['run_id'], ['evaluation_runs.id'], name=op.f('fk_jobs_run_id_evaluation_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs'))
    )
    op.create_index('ix_jobs_claim', 'jobs', ['queue', 'status', 'priority', 'run_after'], unique=False)
    op.create_index('ix_jobs_run_id', 'jobs', ['run_id'], unique=False)
    op.create_index('uq_jobs_active_dedupe_key', 'jobs', ['dedupe_key'], unique=True, postgresql_where=sa.text("dedupe_key IS NOT NULL AND status IN ('queued', 'running')"))
    op.create_table('scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('evaluation_config_id', sa.UUID(), nullable=False),
    sa.Column('criterion_key', sa.Text(), nullable=False),
    sa.Column('dimension', sa.Text(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('method', sa.Text(), nullable=False),
    sa.Column('n_evaluations', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('spread', sa.Float(), nullable=True),
    sa.Column('evaluation_ids', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('used_in_composite', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("dimension IN ('quality', 'coherence', 'reasoning', 'safety', 'robustness', 'cost', 'latency', 'ux')", name=op.f('ck_scores_dimension')),
    sa.CheckConstraint("source IN ('ai', 'rule', 'metric', 'human')", name=op.f('ck_scores_source')),
    sa.CheckConstraint('length(btrim(explanation)) > 0', name=op.f('ck_scores_explanation_required')),
    sa.ForeignKeyConstraint(['evaluation_config_id'], ['evaluation_configs.id'], name=op.f('fk_scores_evaluation_config_id_evaluation_configs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['evaluation_runs.id'], name=op.f('fk_scores_run_id_evaluation_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scores')),
    sa.UniqueConstraint('run_id', 'round', 'evaluation_config_id', 'criterion_key', 'source', name=op.f('uq_scores_run_id_round_evaluation_config_id_criterion_key_source'))
    )
    op.create_index('ix_scores_run_id_round', 'scores', ['run_id', 'round'], unique=False)
    op.create_table('trace_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'ok'"), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('offset_ms', sa.Float(), server_default=sa.text('0'), nullable=False),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('input', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('span_id', sa.Text(), nullable=True),
    sa.Column('parent_span_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('runner', 'adapter', 'otlp', 'api')", name=op.f('ck_trace_events_source')),
    sa.CheckConstraint("status IN ('ok', 'error')", name=op.f('ck_trace_events_status')),
    sa.CheckConstraint("type IN ('run_started', 'context_prepared', 'reasoning', 'message', 'llm_call', 'tool_call', 'tool_result', 'retrieval', 'memory', 'agent_handoff', 'decision', 'error', 'final_answer', 'run_completed', 'custom')", name=op.f('ck_trace_events_type')),
    sa.ForeignKeyConstraint(['parent_id'], ['trace_events.id'], name=op.f('fk_trace_events_parent_id_trace_events'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['evaluation_runs.id'], name=op.f('fk_trace_events_run_id_evaluation_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trace_events')),
    sa.UniqueConstraint('run_id', 'seq', name=op.f('uq_trace_events_run_id_seq'))
    )
    op.create_index('ix_trace_events_run_id_type', 'trace_events', ['run_id', 'type'], unique=False)
    op.create_index('ix_trace_events_span_id', 'trace_events', ['span_id'], unique=False)
    op.create_table('run_errors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=True),
    sa.Column('error_type', sa.Text(), nullable=False),
    sa.Column('severity', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('evaluator_kind', sa.Text(), nullable=True),
    sa.Column('evaluator_key', sa.Text(), nullable=False),
    sa.Column('evaluation_id', sa.UUID(), nullable=True),
    sa.Column('trace_event_id', sa.UUID(), nullable=True),
    sa.Column('criterion_key', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("evaluator_kind IN ('rule', 'metric', 'llm_judge', 'human', 'aggregate')", name=op.f('ck_run_errors_evaluator_kind')),
    sa.CheckConstraint("severity IN ('low', 'medium', 'high', 'critical')", name=op.f('ck_run_errors_severity')),
    sa.ForeignKeyConstraint(['error_type'], ['error_types.code'], name=op.f('fk_run_errors_error_type_error_types'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], name=op.f('fk_run_errors_evaluation_id_evaluations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['evaluation_runs.id'], name=op.f('fk_run_errors_run_id_evaluation_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trace_event_id'], ['trace_events.id'], name=op.f('fk_run_errors_trace_event_id_trace_events'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_run_errors'))
    )
    op.create_index('ix_run_errors_error_type', 'run_errors', ['error_type'], unique=False)
    op.create_index('ix_run_errors_run_id_round', 'run_errors', ['run_id', 'round'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_run_errors_run_id_round', table_name='run_errors')
    op.drop_index('ix_run_errors_error_type', table_name='run_errors')
    op.drop_table('run_errors')
    op.drop_index('ix_trace_events_span_id', table_name='trace_events')
    op.drop_index('ix_trace_events_run_id_type', table_name='trace_events')
    op.drop_table('trace_events')
    op.drop_index('ix_scores_run_id_round', table_name='scores')
    op.drop_table('scores')
    op.drop_index('uq_jobs_active_dedupe_key', table_name='jobs', postgresql_where=sa.text("dedupe_key IS NOT NULL AND status IN ('queued', 'running')"))
    op.drop_index('ix_jobs_run_id', table_name='jobs')
    op.drop_index('ix_jobs_claim', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index('ix_feedback_reports_run_id', table_name='feedback_reports')
    op.drop_index('ix_feedback_reports_experiment_id', table_name='feedback_reports')
    op.drop_index('ix_feedback_reports_benchmark_execution_id', table_name='feedback_reports')
    op.drop_table('feedback_reports')
    op.drop_index('uq_execution_traces_run_id', table_name='execution_traces')
    op.drop_table('execution_traces')
    op.drop_index('ix_evaluations_run_id_round', table_name='evaluations')
    op.drop_index('ix_evaluations_judge_id', table_name='evaluations')
    op.drop_index('ix_evaluations_criterion_key', table_name='evaluations')
    op.drop_table('evaluations')
    op.drop_index('ix_dataset_items_run_id', table_name='dataset_items')
    op.drop_table('dataset_items')
    op.drop_table('composite_scores')
    op.drop_table('experiment_scenarios')
    op.drop_index('ix_evaluation_runs_status', table_name='evaluation_runs')
    op.drop_index('ix_evaluation_runs_scenario_id', table_name='evaluation_runs')
    op.drop_index('ix_evaluation_runs_otel_trace_id', table_name='evaluation_runs')
    op.drop_index('ix_evaluation_runs_experiment_id_arm', table_name='evaluation_runs')
    op.drop_index('ix_evaluation_runs_created_at', table_name='evaluation_runs')
    op.drop_index('ix_evaluation_runs_benchmark_execution_id', table_name='evaluation_runs')
    op.drop_index('ix_evaluation_runs_agent_version_id_created_at', table_name='evaluation_runs')
    op.drop_table('evaluation_runs')
    op.drop_table('judge_cache')
    op.drop_index('ix_experiments_created_at', table_name='experiments')
    op.drop_table('experiments')
    op.drop_table('benchmark_scenarios')
    op.drop_index('ix_benchmark_executions_benchmark_id_created_at', table_name='benchmark_executions')
    op.drop_table('benchmark_executions')
    op.drop_table('benchmark_agents')
    op.drop_index('ix_scenario_versions_content_hash', table_name='scenario_versions')
    op.drop_table('scenario_versions')
    op.drop_index('ix_judges_key_is_latest', table_name='judges')
    op.drop_table('judges')
    op.drop_index('uq_benchmarks_slug', table_name='benchmarks')
    op.drop_table('benchmarks')
    op.drop_index('ix_agent_versions_content_hash', table_name='agent_versions')
    op.drop_table('agent_versions')
    op.drop_table('tool_configurations')
    op.drop_index('uq_scenarios_slug', table_name='scenarios')
    op.drop_index('ix_scenarios_family_id', table_name='scenarios')
    op.drop_index('ix_scenarios_category', table_name='scenarios')
    op.drop_table('scenarios')
    op.drop_index('uq_provider_credentials_name', table_name='provider_credentials')
    op.drop_table('provider_credentials')
    op.drop_table('prompt_versions')
    op.drop_index('ix_model_configurations_content_hash', table_name='model_configurations')
    op.drop_table('model_configurations')
    op.drop_index('ix_evaluation_configs_key_is_latest', table_name='evaluation_configs')
    op.drop_table('evaluation_configs')
    op.drop_index('uq_datasets_slug', table_name='datasets')
    op.drop_table('datasets')
    op.drop_index('uq_api_keys_prefix', table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index('uq_agents_slug', table_name='agents')
    op.drop_table('agents')
    op.drop_index('uq_users_email', table_name='users')
    op.drop_table('users')
    op.drop_table('error_types')
    op.drop_table('criteria')
    op.drop_index('ix_audit_events_target', table_name='audit_events')
    op.drop_index('ix_audit_events_created_at', table_name='audit_events')
    op.drop_index('ix_audit_events_action', table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
